### ISSUE TITLE
图片居中有bug

### ISSUE THREAD

**Issue by 30115776** [justid/InlineAMP#1]
![微信截图_20200308183229](https://user-images.githubusercontent.com/35337225/76161140-45489100-616b-11ea-83ce-21bc3fbfcbf0.png)

图片宽度 1200
显示器分辨率 2.5k

**Comment by justid** [comment]
给个页面链接我看一下

**Comment by 30115776** [comment]
https://www.anuan.org/28.html

**Comment by 30115776** [comment]
在Additional JS 中

Insert to Header：
<script async custom-element="amp-auto-ads"
        src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


Insert to Body：
<amp-auto-ads type="adsense"
        data-ad-client="ca-pub-xxxxxxxxxxxxxxxxxxxxxxxx">
</amp-auto-ads>


是否可以启用谷歌 AMP  AD 广告呢？

**Comment by justid** [comment]
已修复该问题

**Comment by justid** [comment]
支持google amp ad 的

**Comment by 30115776** [comment]
不启用 插件 AMP 可否？

**Comment by 30115776** [comment]
很喜欢这个主题。感谢大佬。

**Comment by justid** [comment]
> 不启用 插件 AMP 可否？

这是专门写给AMP的主题，不启用AMP插件则无法完成AMP化，建议启用

**Comment by justid** [comment]
> 很喜欢这个主题。感谢大佬。

识货

**Comment by 30115776** [comment]
大佬，图片居中问题可以解决以下么。
感觉。。。。好难看

链接：https://www.anuan.org/63.html

**Comment by justid** [comment]
> 大佬，图片居中问题可以解决以下么。
> 感觉。。。。好难看
> 
> 链接：https://www.anuan.org/63.html

可以了 一个样式问题 已修复了

**Comment by 30115776** [comment]
提交几个小问题。
1、文章tags样式不太好看，可以重新排列一下。
地址：http://bs.i5seo.com/1928.html

2、<img>标签，如果存在alt标签且 alt标签且不等于""可以不执行任何操作，否则alt="标题" title="标题" 
原来：<img class="aligncenter" src="xxxxxxxx.jpg" />
改成：<img class="aligncenter" src="xxxxxxxx.jpg" alt="标题" title="标题"  />
利于搜索引擎优化。




请教问题：
不知道主题是否需要开启 Yoast SEO + Glue for Yoast SEO & AMP
这个利于搜索引擎优化（国外关键词排名）
