### ISSUE TITLE
待修复2

### ISSUE THREAD

**Issue by 30115776** [justid/InlineAMP#3]
1、图
标签，如果存在alt标签且 alt标签且不等于""可以不执行任何操作，否则alt="标题" title="标题"
原来：img  class="aligncenter" src="xxxxx.jpg" /
改成：img class="aligncenter"  src="xxxxx.jpg" alt="文章标题" tltle="文章标题" /
利于搜索引擎优化。

2、插件优势，可以写入关键词，分享到Facebook和推特有图片和文字介绍。
如图下

!-- This site is optimized with the Yoast SEO plugin v13.2 - https://yoast.com/wordpress/plugins/seo/ -->
--
  | !-- 通知（仅管理员）：此页不显示元描述，因为没有指定。请填写元描述或进入[SEO - 搜索外观]，并设置一个模板。 -->
  | meta name="robots" content="noindex,follow"/>
  | meta property="og:locale" content="zh_CN" />
  | meta property="og:type" content="article" />
  | meta property="og:title" content="纽约Ahlem眼镜新零售空间 \| Shapeless Studio - 测试" />
  | meta property="og:description" content="洛杉矶的Ahlem Eyewear眼镜店委托Shapeless Studio Architecture＆Interiors，来帮他们设计了其位于纽约市的新零售空间。该现代眼镜品牌专注于巴黎手工制作的以设计为重点的镜架，现已迁入位于SoHo伊丽莎白街的500平方英尺灵活的空间中，该空间可以轻松地变成陈列室、画廊或活动空间。设计师们从该品牌独特的眼镜中获得灵感，尤其是它们的工艺、几何形状和可持续材料的" />
  | meta property="og:url" content="http://bs.i5seo.com/2978.html" />
  | meta property="og:site_name" content="测试" />
  | meta property="article:tag" content="Shapeless" />
  | meta property="article:tag" content="Studio" />
  | meta property="article:tag" content="Studio设计作品" />
  | meta property="article:tag" content="国外" />
  | meta property="article:tag" content="女士" />
  | meta property="article:tag" content="现代" />
  | meta property="article:tag" content="现代装修效果图" />
  | meta property="article:tag" content="纽约Ahlem眼镜新零售空间" />
  | meta property="article:tag" content="购物空间" />
  | meta property="article:section" content="购物空间" />
  | meta property="article:published_time" content="2020-03-09T16:00:00+00:00" />
  | meta property="og:image" content="https://i2.wp.com/small.justeasy.cn/uploads/case/20200309/1583742193368046.jpg" />
  | meta property="og:image:secure_url" content="https://i2.wp.com/small.justeasy.cn/uploads/case/20200309/1583742193368046.jpg" />
  | meta name="twitter:card" content="summary_large_image" />
  |meta name="twitter:description" content="洛杉矶的Ahlem Eyewear眼镜店委托Shapeless Studio Architecture＆Interiors，来帮他们设计了其位于纽约市的新零售空间。该现代眼镜品牌专注于巴黎手工制作的以设计为重点的镜架，现已迁入位于SoHo伊丽莎白街的500平方英尺灵活的空间中，该空间可以轻松地变成陈列室、画廊或活动空间。设计师们从该品牌独特的眼镜中获得灵感，尤其是它们的工艺、几何形状和可持续材料的" />
  | meta name="twitter:title" content="纽约Ahlem眼镜新零售空间 \| Shapeless Studio - 测试" />
  | meta name="twitter:image" content="https://i2.wp.com/small.justeasy.cn/uploads/case/20200309/1583742193368046.jpg" 

3、微信朋友圈的问题如何解决？

搞定这几个问题，到时候把主站数据过滤一次，应该就可以搬过来了。

**Comment by justid** [comment]
image alt 和title这种属性，是属于wordpress的编辑器管理的，与主题无关，tags样式我修复一下

**Comment by justid** [comment]
SEO插件的问题，我不保证一定能用，如果不能用的话，我也不会去做兼容

**Comment by justid** [comment]
微信朋友圈有什么问题？描述问题请清楚一些

**Comment by justid** [comment]
还有 github 有自己的规则，issues不要写什么待修复1待修复2，开源世界里你没有权力要求别人修复，你只能提出你遇到的bug/问题，所以要写明确的标题

**Comment by justid** [comment]
tags的样式问题已修复
