### ISSUE TITLE
图片还是有小问题。

### ISSUE THREAD

**Issue by 30115776** [justid/InlineAMP#4]
当两张图片，或者多张图片在一起的时候。
系统默认处理摆在一排。

比如一篇文章，我有八张图片，那么八张图在一排。
正常其他主题是一张图片一张图片的显示。

img  />img  /img  />img  /img  />img  /img  />img  /img  />img  /

**Comment by justid** [comment]
给出链接看一下，这款主题是适配的wordpress官方默认的古腾堡编辑器。

**Comment by justid** [comment]
你的这个问题多半是直接采集的数据 然后图片又未带有class样式的情况才会出现，如果是这样的话，不在主题需要解决的问题内。

**Comment by 30115776** [comment]
是的，如果是这样的话，那，是否可以替换数据库操作呢？
&gt;<img
这个中间加个换行符？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上8:31
收件人:&nbsp;"justid/InlineAMP"<InlineAMP@noreply.github.com&gt;;
抄送:&nbsp;"文艺青年"<30115776@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [justid/InlineAMP] 图片还是有小问题。 (#4)





 
你的这个问题多半是直接采集的数据 然后图片又未带有class样式的情况才会出现，如果是这样的话，不在主题需要解决的问题内。

**Comment by justid** [comment]
>是的，如果是这样的话，那，是否可以替换数据库操作呢？
理论上是可以的。
这种非主题的问题不属于bug，请不要再开类似的issues了
